language: node_js
node_js:
  - '0.10'
before_install:
  - 'gem install compass'
before_script:
  - 'npm install -g bower grunt-cli codeclimate-test-reporter'
after_success:
  - 'CODECLIMATE_REPO_TOKEN=6dc07a009f8134d7b5989c8231affbdc4dbfad4101249b70af2baf9d4e902405 codeclimate < "coverage/*/lcov.info"'

cache:
  directories:
    - node_modules
    - bower_components

addons:
  sauce_connect:
    username: 'bassman5'
    access_key: 'c3b0d12a-4148-4c13-a62d-a1bc76028876'

env:
  global:
    - SAUCE_USERNAME=bassman5
    - SAUCE_ACCESS_KEY=c3b0d12a-4148-4c13-a62d-a1bc76028876

script: 'grunt travis'
